baseURL : "https://jcematcom.github.io/jce2021/"
languageCode : "es-us"
title : "JCE MatCom 2021"
theme: "PaperMod"

params:
  env: production
  profileMode:
      enabled: true
      title: ""
      subtitle: "Convocatoria para todos los estudiantes de la enseñanza superior en Cuba"
      imageUrl: "img/jornada2021.jpg" # optional
      imageTitle: "JCE Logo" # optional
      imageWidth: 120 # custom size
      imageHeight: 120 # custom size
      buttons:
          - name: Trabajos Presentados
            url: "articulos/"

  socialIcons: # optional
      - name: "github"
        url: "https://github.com/jcematcom"
      - name: "telegram"
        url: "https://t.me/jcematcom"
      - name: "email"
        url: "mailto:jce@matcom.uh.cu"

  images: ["img/jornada2021.jpg"]


menu:
  main:
    - identifier: Artículos
      name: Artículos
      url: /articulos/
      weight: 10
    # - identifier: Convocatoria
    #   name: Convocatoria
    #   url: /convocatoria
    #   weight: 10
    - identifier: Actividades
      name: Actividades Relacionadas
      url: /actividades/
      weight: 20
