baseURL : "https://jcematcom.github.io/jce2021/"
languageCode : "es-us"
title : "JCE MatcoM 2021"
theme: "PaperMod"

params:
    profileMode:
        enabled: true
        title: ""
        subtitle: "Convocatoria para todos los estudiantes de la enseñanza superior en Cuba"
        imageUrl: "img/jornada2021.jpg" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Información
              url: "/convocatoria"

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/jcematcom"
        - name: "telegram"
          url: "https://t.me/jcematcom"
        - name: "email"
          url: "mailto:jce@matcom.uh.cu"

menu:
  main:
    - identifier: Convocatoria
      name: Convocatoria
      url: /convocatoria
      weight: 10
    - identifier: Actividades
      name: Actividades Relacionadas
      url: /actividades/
      weight: 20

